### ISSUE TITLE
ScanBamParam: load all tags

### ISSUE THREAD

**Issue by gevro** [Bioconductor/Rsamtools#34]
Hi, Is there a way to specify with ScanBamParam to load all tags, without having to specify them one by one?

**Comment by LiNk-NY** [comment]
Hi @gevro 

AFAIK, tags are not standard and there is no way to load all tags. 

So you'd have to do:

```sh
samtools view bamfile.bam | head -5 
```
to see what tags are available and select the ones you are interested in. 

Best regards,
Marcel

**Comment by gevro** [comment]
This would be a useful feature.

**Comment by LiNk-NY** [comment]
Perhaps Martin @mtmorgan may have suggestions on how to implement this, if possible.

**Comment by mtmorgan** [comment]
Looking at the first records of a bam file is not sufficient -- a new tag could be introduced into the last record -- so the only way to know all the tags in a bam file is to read it in its entirety. Or, since tags are both optional and only partly standardized, to know ahead of time (e.g., because the aligner documentation indicates that a specific tag is present, and with a specific meaning) that particular tags are present in the file.

Specifying all tags of interest in the `tags=` argument of `ScanBamParam()` is the only way to retrieve 'all' tags.
