### ISSUE TITLE
Support for more recent HTSlib

### ISSUE THREAD

**Issue by matthdsm** [Bioconductor/Rsamtools#41]
Hi,

Are there plans to drop the "included" RHTSlib and depend on the bioconductor package itself? This would enable us the use more modern interfaces (csi, cram, ...).

If not, could you give some pointers where best to start to implement this? Our ultimate goals would be to enable cram compatibility for downstream tools.

Thanks.

**Comment by PeteHaitch** [comment]
It looks like some work has been made on that front but I'm not sure of it's current state: see https://github.com/Bioconductor/Rsamtools/tree/htslib-1.15.1

**Comment by matthdsm** [comment]
AFAIK that branch was merged into master and released, but the docs at bioconductor don't seem to reflect that

**Comment by PeteHaitch** [comment]
Oh you're right, my bad!
I'd misunderstood your query, hopefully @hpages will soon reply.

**Comment by mtmorgan** [comment]
Rhtslib provides the C source code library to htslib. Rsamtools provides the interface between R and htslib. Rsamtools uses the current Rhtslib, but does not implement CRAM and other features -- the code in Rsamtools needs to be updated for that.

There is a branch 'cram' that partially implements cram support; I have rebased it to master. The only guarantee, unfortunately, is that it compiles. We will try to work on this, and any help would be appreciated.

**Comment by hpages** [comment]
I'm not sure I understand the original query either. **Rsamtools** has never "included" **Rhtslib**. 

Here is the timeline:
- A long time ago, and before HTSlib existed, **Rsamtools** was including a copy of the samtools source code (samtools 0.1.17). This was in **Rsamtools** 1.y.z. 
- In 2018, **Rsamtools** was migrated to _depend_ on **Rhtslib**, which at the time contained HTSlib 1.7, and so the copy of the samtools source code got removed from the package. With this change **Rsamtools** version got bumped from 1.y.z to 2.0.0.
- More recently (in May this year), the version of HTSlib contained in **Rhtslib** got updated from 1.7 to 1.15.1. This means that **Rsamtools** and the 22 other Bioconductor packages that depend on **Rhtslib** (via `LinkingTo`) now use HTSlib 1.15.1. Note that because of some backward incompatibilities between HTSlib 1.7 and HTSlib 1.15.1, some of these packages (including **Rsamtools**) had to be patched in order to compile again against the latest **Rhtslib**. All these changes were made in **Rsamtools** 2.13.z, which is part of BioC 3.16 (the current devel version of Bioconductor).

> AFAIK that branch was merged into master and released, but the docs at bioconductor don't seem to reflect that

@matthdsm Can you be more specific about where the doc needs to be updated?

Thanks,
H.

**Comment by matthdsm** [comment]
Hi,

I'm very sorry, but I'm not really sure anymore 🤔. A cursory search shows the latest version of Rsamtools does indeed use Rhtslib, so I think this issue is moot. 
If I ever come back to this and encounter any issues, I'll open a new issue.

Thanks anyway for the reply!
Matthias
